### DISCUSSION TITLE
browser_targets clarification

### DISCUSSION THREAD

**Discussion by emnul** [myFavShrimp/turf#21] [Q&A]
Hi would like to know some additional details about how the `browser_targets` config setting works. If I were to write the following configuration:
```toml
[package.metadata.turf-dev.browser_targets]
chrome = [80, 1, 2]
firefox = 65
```
Does this mean the generated CSS will be compatible for target browser versions >=80.1.2 for Chrome and >=65 for Firefox?
