### ISSUE TITLE
Autoprefixing not working

### ISSUE THREAD

**Issue by lukidoescode** [myFavShrimp/turf#28]
I have a little bit of an issue with the automatic vendor prefixing. I've dug in the source code quite extensively and originally planned to just submit a PR instead of a ticket. But this side quest turned into a main quest and I need to refocus my efforts. In my own project I've resorted to manually add vendor prefixes for now.

# How to Reproduce

Just change `examples/leptos-example/src/hello_leptos.scss` like this:

```scss
@import "color";

.hello-leptos {
    h1 {
        color: $headline-color;
        user-select: none; // add this line
    }

    .hello-world {
        color: blue;
    }
}
```

I know it's nonsensical to make a heading not user selectable. I chose this example to make it very simple to follow and reproduce.

Next, run the example like this: `cd examples/leptos-example && trunk serve` and visit the resulting page in your browser. The currently wrong behavior can be observed and experienced in Safari.

## Expected Result

(not minified and annotated for illustrative purposes, actual result would be minified and possibly feature more extensive vendor prefixing)
```css
.leptos-example_hello-leptos_DfeORJ h1{
    color: #ff69b4;
    user-select: none;
    -webkit-user-select: none; /* <-- THIS ONE and maybe some more */
}

.leptos-example_hello-leptos_DfeORJ .leptos-example_hello-world_y71x44 {
    color: #00f;
}
```

## Actual Result

(not minified, actual result would be minified)
```css
.leptos-example_hello-leptos_DfeORJ h1{
    color: #ff69b4;
    user-select: none;
}

.leptos-example_hello-leptos_DfeORJ .leptos-example_hello-world_y71x44 {
    color: #00f;
}
```

# Why This is an Issue

The Leptos example is already configured and supposed to be compatible with Safari.

What I've tried so far:
- Extensive drug logging in
    - `impl<'a> From<Settings> for lightningcss::printer::PrinterOptions<'a>`
    - `turf_internals::transformer::transform_stylesheet()`
- Implementing browsersquery support for turf into my debug branch and supplying a query that is supposed to guarantee certain vendor prefixing: `browserslist_query = [">0.3%", "last 2 versions", "not dead"]`. My debug printing from above told me that this was working.
- Updating lightningcss to version `=1.0.0-alpha.61` in case it was a bug in that specific version
- Digging into the lightningcss source code to find out if there are any kind of additional undocumented config options or possibly bugs. So far without any success.
