### ISSUE TITLE
[Feature Request] Deteministic ids

### ISSUE THREAD

**Issue by TimTom2016** [myFavShrimp/turf#29]
I am currently creating a simple crate to generate stylesheets at runtime with Leptos. When compiling with ssr and hydrate, I get different IDs. Because of this, I have mismatches between the generated stylesheet and the requested classes in the browser.
If not possible change the default template to use hashes

**Comment by myFavShrimp** [comment]
The class name template system should already support deterministic IDs through hash-based placeholders:

```toml
[package.metadata.turf.class_names]
template = "<original_name>-<name_hash_short><style_sheet_hash_short>"
```

Please let me know if this resolves the issue for you.
