### ISSUE TITLE
No css when using class_name_template

### ISSUE THREAD

**Issue by beckend** [myFavShrimp/turf#5]
Cargo.toml
```toml
[package.metadata.turf]
minify = true
class_name_template = "<original_name>--<id>"
```

Result:
<img width="413" alt="no css" src="https://github.com/myFavShrimp/turf/assets/6056334/43d6b10b-4fa5-4ec5-ac93-b3a42ca38fcb">

There is a space, and then no CSS from that class is applied.

scss file:
```scss
.root {
  position: relative;
}

.imageTop {
  height: auto;
  width: 100%;
}
```
