### ISSUE TITLE
leptos generated CSS is wrong

### ISSUE THREAD

**Issue by beckend** [myFavShrimp/turf#7]
The ids differs and so the CSS never applies.

cargo.toml
```toml
[package]
name = 'this-app'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = ['cdylib', 'rlib']

[dependencies]
anyhow = '1.0.75'
axum = { version = '0.6.4', features = ['headers', 'http2'], optional = true }
blake3 = { version = "1.4.1", optional = true }
cfg-if = '1'
console_error_panic_hook = '0.1'
console_log = '1'
http = '0.2.8'
leptos = { version = '0.5.0-beta', features = ['nightly'] }
leptos_axum = { version = '0.5.0-beta', optional = true }
leptos_i18n = { path = './.internals/deps/VCS/leptos_i18n/leptos_i18n' }
leptos_meta = { version = '0.5.0-beta', features = ['nightly'] }
leptos_router = { version = '0.5.0-beta', features = ['nightly'] }
log = '0.4'
moka = { version = "0.11.3", features = ["future"], optional = true }
once_cell = "1.18.0"
serde = { version = '1.0.183', features = ['derive'] }
serde_json = "1.0.105"
simple_logger = '4'
thiserror = "1.0.38"
time = { version = '0.3.25', features = ['wasm-bindgen'] }
tokio = { version = '1.25.0', optional = true }
tower = { version = '0.4.13', optional = true }
tower-http = { version = '0.4', features = ['fs'], optional = true }
tracing = { version = '0.1.37', features = ['async-await', 'log'] }
tracing-subscriber = { version = "0.3.17", features = ["time", "local-time"] }
tracing-subscriber-wasm = { version = '0.1.0', optional = true }
turf = { version = "0.6.1", features = ["once_cell"] }
url = { version = "2.4.0", optional = true }
uuid = { version = "1.4.1", features = [
  "fast-rng",
  "v4",
  "macro-diagnostics",
  "wasm-bindgen",
] }
validator = { version = "0.16.1", features = [
  "derive",
  "phone",
  "phonenumber",
] }
wasm-bindgen = '=0.2.87'

[features]
hydrate = [
  'leptos/hydrate',
  'leptos_meta/hydrate',
  'leptos_router/hydrate',
  'dep:tracing-subscriber-wasm',
]
ssr = [
  'dep:axum',
  'dep:blake3',
  'dep:moka',
  'dep:tokio',
  'dep:tower',
  'dep:tower-http',
  'dep:leptos_axum',
  'dep:url',
  'leptos/ssr',
  'leptos_meta/ssr',
  'leptos_router/ssr',
]
all = ['ssr', 'hydrate']

```

```rust
turf::style_sheet!("src/components/portal.scss");
```

```scss
.opening {
  transition: all 1s;
}

.closing {
  transition: all 1s;
}

.background {
  width: 100%;
  height: 100%;
  position: relative;
}

.content {
  position: absolute;
  top: 2rem;
  left: 2rem;
  right: 2rem;
  bottom: 2rem;
  border: 2px solid red;
  border-radius: 5px;
  z-index: 10;
}
```

<img width="200" alt="Screenshot 2023-08-24 165009" src="https://github.com/myFavShrimp/turf/assets/6056334/ff154cb6-98e0-4a1b-af02-9f1444cc90e5">

<img width="428" alt="Screenshot 2023-08-24 165122" src="https://github.com/myFavShrimp/turf/assets/6056334/0cbe14e4-d52f-4473-8293-4be22dfe5c89">
